## Two functions(makeCacheMatrix and cacheSolve) to cache the inverse of a matrix

## makeCacheMatrix: 
## This function creates a special "matrix" object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
  ##initialize the inverse matrix
  invMat <- NULL
  
  #define the set function for the matrix
  set <- function(y) {
    x <<- y
    invMat <<- NULL
  }
  
  ##define the return matrix object by defining it as get
  get <- function() {
    x ##return special matrix
  }
  
  ##setting the inverse matrix 
  setInvMat <- function(inverseM) {
    invMat <<- inverseM ##assign the inverse matrix to the environment var 
  }
  
  ##define the function for returning the inverse matrix
  getInvMat <- function() {
    invMat
  }
  
  ##put all defined function into a list for future call within the environment
  list(set = set,
       get = get, 
       setInvMat = setInvMat, 
       getInvMat = getInvMat)
}


## cacheSolve(): computes the inverse of the "matrix" returned by makeCacheMatrix(). 
## If the inverse has already been calculated and the matrix has not changed, it’ll retrieves the inverse from the cache directly

cacheSolve <- function(x, ...) {
  ## 1. - get the available inverse of the original matrix generated by makeCacheMatrix
  inv <- x$getInvMat()
  
  ## 2. Verified if the inverse has already been calculated
  if (!is.null(inv)){
    ## get it from the cache and skips the computation. 
    message("getting cached data")
    return(inv)
  }
  
  ## 3. Else inverse matrix null or matrix change, calculates the inverse 
  mdata <- x$get()
  inv <- solve(mdata, ...)
  
  ## sets the value of the inverse in the cache via the setinv function.
  x$setInvMat(inv)
  
  ## Return a matrix that is the inverse of "x"
  return(inv)
}